version: "3"

services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: log-engine-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: logpassword123
      POSTGRES_DB: log_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    command: postgres -c shared_preload_libraries=timescaledb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
